import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { WindowManagerProvider } from "@/components/windowManager";
import Dock from "@/components/navigation/dock";
import Desktop from "@/components/desktop";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <WindowManagerProvider>
          <div className="os-container">
            <Desktop />
            {children}
            <Dock />
          </div>
        </WindowManagerProvider>
      </body>
    </html>
  );
}
