import { MeshGradientComponent } from "@/components/MeshGradient";
import { MusicPlayer } from "@/components/MusicPlayer";
import { RouteTransitionSync } from "@/components/RouteTransitionSync";
import { settings } from "@/lib/settings";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ExternalLinks, Navigation } from "../components/navigation";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Preload portrait image globally so it's cached before visiting /hello */}
        <link rel="preload" as="image" href="/me.png" fetchPriority="high" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black h-dvh relative`}
      >
        <RouteTransitionSync />
        <MeshGradientComponent
          speed={settings.background.speed}
          style={{
            position: "fixed",
            top: 0,
            left: 0,
            zIndex: 0,
            width: "100%",
            height: "100%",
          }}
        />

        {/* Main content container with max-width constraint */}
        <main className="relative z-20 max-w-screen-2xl mx-auto min-h-dvh">
          <Navigation />
          <div className="text-white">{children}</div>

          {/* Music Player - Positioned absolutely on bottom left */}
          <MusicPlayer />

          {/* External Links - Positioned absolutely within the max-width container */}
          <ExternalLinks />
        </main>
      </body>
    </html>
  );
}
